-- RUN THIS SCRIPT IN YOUR SUPABASE DASHBOARD SQL EDITOR TO ENABLE ANALYTICS
-- Link: https://supabase.com/dashboard/project/_/sql/new

-- 1. Create page_visits table
create table if not exists public.page_visits (
  id bigint generated by default as identity primary key,
  path text not null,
  visit_count bigint default 0,
  last_visited_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table public.page_visits enable row level security;

-- 3. Create policy for public read access (so you can view stats)
-- We drop it first to be safe
drop policy if exists "Allow public read access to page_visits" on public.page_visits;
create policy "Allow public read access to page_visits"
  on public.page_visits for select
  using (true);

-- 4. Create increment function (RPC)
create or replace function increment_page_visit(page_path text)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.page_visits (path, visit_count, last_visited_at)
  values (page_path, 1, now())
  on conflict (path)
  do update set 
    visit_count = page_visits.visit_count + 1,
    last_visited_at = now();
end;
$$;

-- 5. Add unique constraint if it doesn't exist (it's required for the ON CONFLICT above)
do $$ 
begin
  if not exists (select 1 from pg_constraint where conname = 'page_visits_path_key') then
    alter table public.page_visits add constraint page_visits_path_key unique (path);
  end if;
end $$;

-- 6. Grant execute permissions
grant execute on function increment_page_visit(text) to anon, authenticated, service_role;

-- 7. Notify Schema Reload
NOTIFY pgrst, 'reload schema';
