-- Create a table to store page visits
create table if not exists page_visits (
  id bigint generated by default as identity primary key,
  path text not null,
  visit_count bigint default 0,
  last_visited_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table page_visits enable row level security;

-- Create policy to allow reading visits (publicly or authenticated, we'll keep it public for the stats page for now or restrict later)
create policy "Allow public read access to page_visits"
  on page_visits for select
  using (true);

-- Create policy to allow updating visits (server-side only ideally, but for now we might need public if called from client directly, 
-- though we are using server actions so we can use service role. 
-- However, standard practice for simple counters: allow insert/update if needed or just rely on service role in actions).
-- Since we use Supabase client in server actions which might use the user's session, 
-- we often need a policy. 
-- BUT, best practice for "internal" counters is to use a Postgres function (RPC) that anybody can call to increment, 
-- or use the service role key in the server action. 
-- Let's stick to Service Role in Server Action for writing, so no write policy needed for "anon".
-- Actually, wait, if I use a standard supabase client in a server action, it acts as the user.
-- If I use `createClient` from `@supabase/ssr` in a server action, it runs as `anon` or the logged-in user.
-- So I should probably allow `anon` to insert/update IF I want to do it directly, OR better:
-- Create a secure RPC function to increment counter.

create or replace function increment_page_visit(page_path text)
returns void
language plpgsql
security definer
as $$
begin
  insert into page_visits (path, visit_count, last_visited_at)
  values (page_path, 1, now())
  on conflict (path) -- We need a unique constraint for this to work
  do update set 
    visit_count = page_visits.visit_count + 1,
    last_visited_at = now();
end;
$$;

-- Add unique constraint to path
alter table page_visits add constraint page_visits_path_key unique (path);

-- Grant execute on function to anon and authenticated
grant execute on function increment_page_visit(text) to anon, authenticated, service_role;
